WebAutomat/Models/AutomatViewModel.cs
using System.Collections.Generic;
using WebAutomat.DataAccess.Entity;

namespace WebAutomat.Models
{
    public class AutomatViewModel
    {
        public AutomatViewModel(IEnumerable<Coin> C, IEnumerable<Drink> D, int T)
        {
            Coins = C;
            Drinks = D;
            Total = T;
        }
        public IEnumerable<Coin> Coins
        { get; set; }

        public IEnumerable<Drink> Drinks
        { get; set; }

        public int Total
        { get; set; }
    }
}

WebAutomat/Models/ChangeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAutomat.Models
{
    public class ChangeViewModel
    {
        public int Status; //1 - успешно, 0 - не хватает монет для сдачи
        public Dictionary<string, int> Wallet;

        public ChangeViewModel()
        {
            Wallet = new Dictionary<string, int>();
        }
    }
}

WebAutomat/Controllers/AdminController.cs
using System.Web;
using System.Web.Mvc;
using WebAutomat.BusinessLogic.Interfaces;
using WebAutomat.DataAccess.Entity;
using WebAutomat.Infrastructure;
using WebAutomat.Models;

namespace WebAutomat.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IDrinkService DrinkService;
        private ICoinService CoinService;

        public AdminController(IDrinkService ds, ICoinService cs)
        {
            DrinkService = ds;
            CoinService = cs;
        }

        [Admin] //Фильтр в котором происходит аутентификация
        [AllowAnonymous]
        public ActionResult Index()
        {
            var drinks = DrinkService.GetAll();
            var coins = CoinService.GetAll();
            return View(new AutomatViewModel(coins, drinks, 0));
        }

        public ViewResult Edit(int Id) //Загрузка информации о напитке для редактирования
        {
            return View(DrinkService.GetDrink(Id));
        }

        [HttpPost]
        public ActionResult Edit(Drink drink, HttpPostedFileBase image = null) //Сохранение изменнеий по напитку
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    drink.ImageType = image.ContentType;
                    drink.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(drink.ImageData, 0, image.ContentLength);
                }
                TempData["message"] = DrinkService.SaveDrink(drink);
                return RedirectToAction("Index");
            }
            else
            {
                return View(drink);
            }
        }

        public ViewResult Create() //Создание напитка
        {
            return View("Edit", new Drink());
        }

        [HttpPost]
        public ActionResult Delete(int ID) //Удаление напитка
        {
            Drink deletedDrink = DrinkService.DeleteDrink(ID);
            if (deletedDrink != null)
            {
                TempData["message"] = string.Format("Напиток \"{0}\" был удален",
                    deletedDrink.Name.Trim());
            }
            return RedirectToAction("Index");
        }

        public FileContentResult GetImage(int Id) //Получение изображения напитка по ID
        {
            return DrinkService.GetDrinkImage(Id);
        }

        public ActionResult EditCoin(int CoinId, int CoinCount, bool CoinBlock) //Сохранение изменений по монетам
        {
            CoinService.EditCoin(CoinId, CoinCount, CoinBlock);
            return RedirectToAction("Index");
        }
    }
}

WebAutomat/Controllers/DrinksController.cs
using WebAutomat.BusinessLogic.Interfaces;
using System.Web.Mvc;
using WebAutomat.Models;
using System.Collections.Generic;

namespace WebAutomat.Controllers
{
    public class DrinksController : Controller
    {
        private IDrinkService DrinkService;
        private ICoinService CoinService;

        public DrinksController(IDrinkService ds, ICoinService cs)
        {
            DrinkService = ds;
            CoinService = cs;
        }

        public ActionResult Index()
        {
            var drinks = DrinkService.GetAll();
            var coins = CoinService.GetAll();
            return View(new AutomatViewModel(coins, drinks, GetTotal()));
        }

        public FileContentResult GetImage(int Id) //Получение изображения напитка по ID
        {
            return DrinkService.GetDrinkImage(Id);
        }

        public ActionResult AddCoin(int CoinId) //Добавление монеты
        {
            int cost = CoinService.AddCoin(CoinId);
            ChangeTotal(cost);

            return RedirectToAction("Index");
        }

        public ActionResult GetDrink(int DrinkId) //Покупка напитка
        {
            int cost = DrinkService.BuyDrink(DrinkId);
            if (cost > 0)
            {
                ChangeTotal(-cost);
            }

            return RedirectToAction("Index");
        }

        public ActionResult GetChange() //Возврат сдачи
        {
            Dictionary<string, int> dict = CoinService.GetChange(GetTotal());
            int total = dict["$remain"];
            dict.Remove("$remain");
            SetTotal(total);
            var change = new ChangeViewModel();
            change.Status = total == 0 ? 1 : 0;
            change.Wallet = dict;

            TempData["message"] = change;

            return RedirectToAction("Index");
        }

        int GetTotal() //Получение веденной пользователем суммы из сессии
        {
            if (Session["Total"] != null)
                return (int)Session["Total"];
            else
                return 0;
        }

        void ChangeTotal(int diff) //Изменение веденной пользователем суммы на сумму diff
        {
            Session["Total"] = GetTotal() + diff;
        }

        void SetTotal(int total) //Изменение веденной пользователем суммы
        {
            Session["Total"] = total;
        }
    }
}

WebAutomat/Views/Admin/Edit.cshtml
@model WebAutomat.DataAccess.Entity.Drink

@{
    ViewBag.Title = "Редактирование напитка";
}


<div class="container">
    <div class="panel-heading">
        @if (@Model.ID == 0)
        {
            <h3>Добавление напитка</h3>
        }
        else
        {
            <h3>Редактирование напитка «@Model.Name»</h3>
        }
    </div>

    @using (Html.BeginForm("Edit", "Admin",
                FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ID)
            @foreach (var property in ViewData.ModelMetadata.Properties) //Цикл по полям модели напитка
            {
                switch (property.PropertyName)
                {
                    case "ID":
                    case "ImageData":
                    case "ImageType":
                        break;
                    default:
                        <div class="form-group">
                            <label>@property.DisplayName</label>
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            @Html.HiddenFor(m => m.ImageData)
            @Html.HiddenFor(m => m.ImageType)
            <div class="form-group">
                <div style="position:relative;">
                    <label>Картинка</label>
                    <a class='btn btn-link' href='javascript:;'>
                        Выберите файл...
                        <input type="file" name="Image" size="40"
                                style="position:absolute;z-index:2;top:0;
                            left:0;filter: alpha(opacity=0); opacity:0;
                            background-color:transparent;color:transparent;"
                                onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">Нет картинки</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                            src="@Url.Action("GetImage", "Admin",
                    new { Model.ID })" />
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-success" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
                {
                    @class = "btn btn-primary"
                })
        </div>
    }
</div>

WebAutomat/Views/Admin/Index.cshtml
@model WebAutomat.Models.AutomatViewModel

@{
    ViewBag.Title = "Настройки автомата";
}


<div class="col-md-3">
    <div class="panel-heading">
        <h5 class="text-center">Настройка монет</h5>
    </div>
    <div class="panel-body">
        <div id="loading" style="display:none; color:dodgerblue; font-weight:bold;">
            <p>Идет сохранение...</p>
        </div>
        @foreach (var item in Model.Coins) //Данные по монетам сохраняются через AJAX
        {
            using (Ajax.BeginForm("EditCoin", "Admin", new AjaxOptions {LoadingElementId="loading", 
                                                        LoadingElementDuration=1000 },
                    new { @class = "form-inline row" }))
            {
                <form class="form-inline row" role="form">
                    <input type="hidden" name="CoinId" value=@item.ID>
                    <div class="form-group col-md-7">
                        <label class="col-md-6">@item.Name</label>
                        <div class="col-md-6">
                            <input name="CoinCount" class="form-control" type="number" min=0 id="InputNum" value=@item.Count onkeypress="Validate">
                        </div>
                    </div>
                    <div class="form-group col-md-1">
                        @Html.CheckBox("CoinBlock", item.Block)
                    </div>
                    <div class="form-group col-md-3">
                        <button class="btn btn-primary btn-sm">Сохранить</button>
                    </div>

                </form>
            }
        }
    </div>
</div>
<div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h5 class="text-center">Настройка автомата</h5>
        </div>
        <div class="panel-body">
            @if (TempData["message"] != null) //Если есть сообщени о редактировании или удалении то выводится
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            <table class="table table-striped table-condensed table-bordered">
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Название</th>
                    <th class="text-center">Цена</th>
                    <th class="text-center">Кол-во</th>
                    <th class="text-center">Изображение</th>
                    <th></th>
                </tr>
                @foreach (var item in Model.Drinks)
                {
                    <tr>
                        <td class="text-center">@item.ID</td>
                        <td class="text-center">@Html.ActionLink(item.Name, "Edit", new { item.ID })</td>
                        <td class="text-center">@item.Cost</td>
                        <td class="text-center">@item.Count</td>
                        <td class="text-center">
                            <img class="img-thumbnail" width="75" height="75"
                                 src="@Url.Action("GetImage", "Admin", new { item.ID })" />
                        </td>
                        <td class="text-center">
                            @using (Html.BeginForm("Delete", "Admin"))
                            {
                                @Html.Hidden("Id", item.ID)
                                <input type="submit"
                                       class="btn btn-primary btn-xs"
                                       value="Удалить"
                                       onclick="return confirm('Вы уверены что хотите удалить напиток?')"/>
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Добавить напиток", "Create", null,
                new { @class = "btn btn-success" })
            <br />
            <br />
        </div>
    </div>
</div>

WebAutomat/Views/Drinks/Index.cshtml
@model WebAutomat.Models.AutomatViewModel

@{
    ViewBag.Title = "Настройки автомата";
    WebAutomat.Models.ChangeViewModel Change;
    if (TempData["message"] != null) //Если пользователь запросил сдачу
    {
        Change = (WebAutomat.Models.ChangeViewModel) TempData["message"];
    }
    else
    {
        Change = null;
    }

}

<div class="col-md-3">
    <div class="panel-heading">
        <h5 class="text-center">Монеты</h5>
    </div>
    <div class="panel-body">
        <div class="container">
            @foreach (var item in Model.Coins)
            {
                using (Html.BeginForm("AddCoin", "Drinks"))
                {
                    @Html.Hidden("CoinId", item.ID)
                    <div class="btn-group-vertical col-md-12">
                        @if (item.Block) //Если монета заблокирована, то блокируется кнопка приема монет
                        {
                            <button type="submit" disabled class="btn btn-primary">@item.Name</button>
                        }
                        else
                        {                           
                            <button type="submit" class="btn btn-primary">@item.Name</button>
                        }
                    </div>
                }
            }
            <label class="alert">Итого: @Model.Total</label>
        </div>
        <div class="container">
            @using (Html.BeginForm("GetChange", "Drinks"))
            {
                <div class="btn-group-vertical col-md-12">

                    @if (Model.Total == 0) //Если внесенная сумма равна 0, то блокируется кнопка сдачи
                    {
                        <button type="submit" disabled class="btn btn-success">Забрать сдачу</button>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-success">Забрать сдачу</button>
                    }
                </div>
            }
            @if (Change != null) //Если пользователь запросил сдачу
            {
                <div class="alert">
                    @if (Change.Status == 0)
                    {
                        <p>Недостаточно монет для сдачи</p>
                    }
                    @if (Change.Wallet.Count > 0)
                    {
                        <p>Сдача</p>
                        <ui>
                            @foreach (var item in Change.Wallet)
                            {
                                <li>@item.Key.Trim() - @item.Value</li>
                            }
                        </ui>
                    }
                </div>
            }
        </div>
    </div>
</div>
<div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h5 class="text-center">Напитки</h5>
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <th width="33%"></th>
                    <th width="33%"></th>
                    <th width="33%"></th>
                </tr>
                <!-- Напитки выводятся в виде таблицы с тремя столбцами -->
                @for (int i = 0; i < Math.Ceiling((double)Model.Drinks.Count() / 3); i++) //Определение номера строки
                {
                    <tr>
                        @for (int j = 3 * i; j < 3 * i + 3; j++) //Заполнение столбцов
                        {
                            if (j < Model.Drinks.Count())
                            {
                                <td>
                                    <div class="row">
                                        <div>
                                            <!-- Если недостаточно средств или напиток заночился, то картинка с напитком блокируется -->
                                            @if ((Model.Drinks.ElementAt(j).Cost <= Model.Total) && @Model.Drinks.ElementAt(j).Count > 0)
                                            {
                                                <a href="@Url.Action("GetDrink", "Drinks", new { DrinkId = Model.Drinks.ElementAt(j).ID})">
                                                    <img class="img-thumbnail" width="110" height="110"
                                                         src="@Url.Action("GetImage", "Drinks", new { Model.Drinks.ElementAt(j).ID })" />
                                                </a>
                                            }
                                            else
                                            {
                                                <img class="img-thumbnail" style="background-color: red;" width="110" height="110"
                                                     src="@Url.Action("GetImage", "Drinks", new { Model.Drinks.ElementAt(j).ID })" />
                                            }
                                        </div>
                                        <div>
                                            <label class="lead">@Model.Drinks.ElementAt(j).Name</label><br>
                                            <label class="lead">Цена: @Model.Drinks.ElementAt(j).Cost</label><br>
                                            <label class="lead">Кол-во: @Model.Drinks.ElementAt(j).Count</label>
                                        </div>
                                    </div>
                                </td>
                            }
                        }
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

WebAutomat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <style>
        #InputNum {
            width: 90px;
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <h2 class="text-light">Автомат по продаже напитков</h2>
    </nav>
    <div class="row panel">
        @RenderBody()
    </div>
</body>
</html>